# Generated by Django 2.0.3 on 2018-03-31 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='intro',
            field=models.CharField(blank=True, max_length=511, null=True),
        ),
    ]
